name: Update data & publish

on:
  schedule:
    - cron: '5 * * * *'   # 每小時第 5 分
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: update-data
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - run: python -m pip install -U pip
      - run: pip install pandas requests python-dotenv xmltodict

      - name: Update caches & export JSON
        env:
          CWA_TOKEN: ${{ secrets.CWA_TOKEN }}
          EXPORT_DAYS: '30'
          HOURS_PER_RUN: '168'
        run: python app/ci_update.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data docs/data
          git commit -m "chore: auto update data [skip ci]" || echo "no changes"
          git push
